const StudentData = {
  students: [
    { Name: "Evelyn", Project: "SCRUM", Difficulty: "3", Rating: "4" },
    { Name: "Evelyn", Project: "W1D1-1", Difficulty: "3", Rating: "3" },
    { Name: "Evelyn", Project: "W1D2-1", Difficulty: "1", Rating: "3" },
    { Name: "Evelyn", Project: "W1D2-2", Difficulty: "1", Rating: "4" },
    { Name: "Evelyn", Project: "W1D2-3", Difficulty: "2", Rating: "3" },
    { Name: "Evelyn", Project: "W1D2-4", Difficulty: "3", Rating: "4" },
    { Name: "Evelyn", Project: "W1D2-5", Difficulty: "3", Rating: "4" },
    { Name: "Evelyn", Project: "W1D3-1", Difficulty: "3", Rating: "4" },
    { Name: "Evelyn", Project: "W1D3-2", Difficulty: "3", Rating: "4" },
    { Name: "Evelyn", Project: "W1D3-4", Difficulty: "4", Rating: "4" },
    { Name: "Evelyn", Project: "W1D3-5", Difficulty: "4", Rating: "4" },
    {
      Name: "Evelyn",
      Project: "W1D3 - Project - Guess-the-number",
      Difficulty: "5",
      Rating: "5",
    },
    { Name: "Evelyn", Project: "W1D4-1", Difficulty: "4", Rating: "5" },
    {
      Name: "Evelyn",
      Project: "W1D4 - Project - Kleurentoggle",
      Difficulty: "3",
      Rating: "4",
    },
    {
      Name: "Evelyn",
      Project: "W1D5 - Project - Galgje",
      Difficulty: "3",
      Rating: "3",
    },
    { Name: "Evelyn", Project: "W2D1-1", Difficulty: "1", Rating: "5" },
    { Name: "Evelyn", Project: "W2D1-2", Difficulty: "2", Rating: "5" },
    { Name: "Evelyn", Project: "W2D2-1", Difficulty: "3", Rating: "4" },
    { Name: "Evelyn", Project: "W2D2-2", Difficulty: "3", Rating: "4" },
    { Name: "Evelyn", Project: "W2D2-3", Difficulty: "3", Rating: "4" },
    { Name: "Evelyn", Project: "W2D3-1", Difficulty: "4", Rating: "4" },
    { Name: "Evelyn", Project: "W2D3-2", Difficulty: "1", Rating: "3" },
    { Name: "Evelyn", Project: "W2D3-3", Difficulty: "4", Rating: "4" },
    { Name: "Evelyn", Project: "W2D4-1", Difficulty: "1", Rating: "3" },
    { Name: "Evelyn", Project: "W2D4-2", Difficulty: "4", Rating: "4" },
    { Name: "Evelyn", Project: "W2D4-3", Difficulty: "1", Rating: "3" },
    {
      Name: "Evelyn",
      Project: "W2D5 - Project - Filmzoeker",
      Difficulty: "3",
      Rating: "4",
    },
    { Name: "Evelyn", Project: "W3D1-1", Difficulty: "3", Rating: "4" },
    { Name: "Evelyn", Project: "W3D1-2", Difficulty: "2", Rating: "4" },
    { Name: "Evelyn", Project: "W3D1-3", Difficulty: "3", Rating: "4" },
    { Name: "Evelyn", Project: "W3D1-4", Difficulty: "3", Rating: "3" },
    { Name: "Evelyn", Project: "W3D2-1", Difficulty: "2", Rating: "4" },
    { Name: "Evelyn", Project: "W3D2-2", Difficulty: "3", Rating: "3" },
    { Name: "Evelyn", Project: "W3D2-3", Difficulty: "3", Rating: "5" },
    { Name: "Evelyn", Project: "W3D3-1", Difficulty: "4", Rating: "4" },
    { Name: "Evelyn", Project: "W3D3-2", Difficulty: "4", Rating: "5" },
    { Name: "Evelyn", Project: "W3D3-3", Difficulty: "3", Rating: "5" },
    { Name: "Evelyn", Project: "W3D3-4", Difficulty: "4", Rating: "5" },
    { Name: "Evelyn", Project: "W3D4-1", Difficulty: "5", Rating: "5" },
    { Name: "Evelyn", Project: "W3D4-2", Difficulty: "1", Rating: "5" },
    {
      Name: "Evelyn",
      Project: "W3D5 - Project - Todo-List",
      Difficulty: "2",
      Rating: "5",
    },
    { Name: "Evelyn", Project: "W4D2-1", Difficulty: "1", Rating: "5" },
    { Name: "Evelyn", Project: "W4D2-2", Difficulty: "1", Rating: "5" },
    { Name: "Evelyn", Project: "W4D2-3", Difficulty: "1", Rating: "5" },
    { Name: "Evelyn", Project: "W4D2-4", Difficulty: "1", Rating: "5" },
    { Name: "Evelyn", Project: "W4D3-1", Difficulty: "1", Rating: "5" },
    { Name: "Evelyn", Project: "W4D3-2", Difficulty: "1", Rating: "5" },
    { Name: "Evelyn", Project: "W4D3-3", Difficulty: "1", Rating: "5" },
    { Name: "Evelyn", Project: "W4D3-4", Difficulty: "1", Rating: "5" },
    { Name: "Evelyn", Project: "W4D3-5", Difficulty: "1", Rating: "5" },
    {
      Name: "Evelyn",
      Project: "W4D3 - Project - Next-Level CSS",
      Difficulty: "1",
      Rating: "5",
    },
    { Name: "Evelyn", Project: "W5D4-1", Difficulty: "3", Rating: "4" },
    {
      Name: "Evelyn",
      Project: "W5D5 - Project - Lil_Playlist",
      Difficulty: "4",
      Rating: "3",
    },
    { Name: "Evelyn", Project: "W6D1-1", Difficulty: "5", Rating: "5" },
    { Name: "Evelyn", Project: "W6D2-1", Difficulty: "4", Rating: "3" },
    {
      Name: "Evelyn",
      Project: "W6D2 - Project - Eindopdracht",
      Difficulty: "5",
      Rating: "5",
    },
    { Name: "Aranka", Project: "SCRUM", Difficulty: "1", Rating: "1" },
    { Name: "Aranka", Project: "W1D1-1", Difficulty: "4", Rating: "3" },
    { Name: "Aranka", Project: "W1D2-1", Difficulty: "3", Rating: "1" },
    { Name: "Aranka", Project: "W1D2-2", Difficulty: "3", Rating: "2" },
    { Name: "Aranka", Project: "W1D2-3", Difficulty: "4", Rating: "1" },
    { Name: "Aranka", Project: "W1D2-4", Difficulty: "2", Rating: "3" },
    { Name: "Aranka", Project: "W1D2-5", Difficulty: "4", Rating: "2" },
    { Name: "Aranka", Project: "W1D3-1", Difficulty: "3", Rating: "2" },
    { Name: "Aranka", Project: "W1D3-2", Difficulty: "2", Rating: "1" },
    { Name: "Aranka", Project: "W1D3-4", Difficulty: "1", Rating: "2" },
    { Name: "Aranka", Project: "W1D3-5", Difficulty: "4", Rating: "1" },
    {
      Name: "Aranka",
      Project: "W1D3 - Project - Guess-the-number",
      Difficulty: "2",
      Rating: "3",
    },
    { Name: "Aranka", Project: "W1D4-1", Difficulty: "3", Rating: "2" },
    {
      Name: "Aranka",
      Project: "W1D4 - Project - Kleurentoggle",
      Difficulty: "4",
      Rating: "3",
    },
    {
      Name: "Aranka",
      Project: "W1D5 - Project - Galgje",
      Difficulty: "4",
      Rating: "1",
    },
    { Name: "Aranka", Project: "W2D1-1", Difficulty: "2", Rating: "4" },
    { Name: "Aranka", Project: "W2D1-2", Difficulty: "4", Rating: "4" },
    { Name: "Aranka", Project: "W2D2-1", Difficulty: "3", Rating: "4" },
    { Name: "Aranka", Project: "W2D2-2", Difficulty: "3", Rating: "4" },
    { Name: "Aranka", Project: "W2D2-3", Difficulty: "1", Rating: "4" },
    { Name: "Aranka", Project: "W2D3-1", Difficulty: "4", Rating: "3" },
    { Name: "Aranka", Project: "W2D3-2", Difficulty: "4", Rating: "1" },
    { Name: "Aranka", Project: "W2D3-3", Difficulty: "1", Rating: "1" },
    { Name: "Aranka", Project: "W2D4-1", Difficulty: "1", Rating: "4" },
    { Name: "Aranka", Project: "W2D4-2", Difficulty: "2", Rating: "3" },
    { Name: "Aranka", Project: "W2D4-3", Difficulty: "2", Rating: "3" },
    {
      Name: "Aranka",
      Project: "W2D5 - Project - Filmzoeker",
      Difficulty: "2",
      Rating: "2",
    },
    { Name: "Aranka", Project: "W3D1-1", Difficulty: "4", Rating: "2" },
    { Name: "Aranka", Project: "W3D1-2", Difficulty: "3", Rating: "2" },
    { Name: "Aranka", Project: "W3D1-3", Difficulty: "1", Rating: "4" },
    { Name: "Aranka", Project: "W3D1-4", Difficulty: "1", Rating: "3" },
    { Name: "Aranka", Project: "W3D2-1", Difficulty: "1", Rating: "3" },
    { Name: "Aranka", Project: "W3D2-2", Difficulty: "2", Rating: "3" },
    { Name: "Aranka", Project: "W3D2-3", Difficulty: "2", Rating: "3" },
    { Name: "Aranka", Project: "W3D3-1", Difficulty: "2", Rating: "2" },
    { Name: "Aranka", Project: "W3D3-2", Difficulty: "4", Rating: "3" },
    { Name: "Aranka", Project: "W3D3-3", Difficulty: "3", Rating: "3" },
    { Name: "Aranka", Project: "W3D3-4", Difficulty: "1", Rating: "3" },
    { Name: "Aranka", Project: "W3D4-1", Difficulty: "1", Rating: "1" },
    { Name: "Aranka", Project: "W3D4-2", Difficulty: "3", Rating: "2" },
    {
      Name: "Aranka",
      Project: "W3D5 - Project - Todo-List",
      Difficulty: "1",
      Rating: "1",
    },
    { Name: "Aranka", Project: "W4D2-1", Difficulty: "2", Rating: "1" },
    { Name: "Aranka", Project: "W4D2-2", Difficulty: "3", Rating: "2" },
    { Name: "Aranka", Project: "W4D2-3", Difficulty: "2", Rating: "2" },
    { Name: "Aranka", Project: "W4D2-4", Difficulty: "3", Rating: "4" },
    { Name: "Aranka", Project: "W4D3-1", Difficulty: "2", Rating: "1" },
    { Name: "Aranka", Project: "W4D3-2", Difficulty: "4", Rating: "4" },
    { Name: "Aranka", Project: "W4D3-3", Difficulty: "3", Rating: "1" },
    { Name: "Aranka", Project: "W4D3-4", Difficulty: "3", Rating: "1" },
    { Name: "Aranka", Project: "W4D3-5", Difficulty: "4", Rating: "3" },
    {
      Name: "Aranka",
      Project: "W4D3 - Project - Next-Level CSS",
      Difficulty: "4",
      Rating: "4",
    },
    { Name: "Aranka", Project: "W5D4-1", Difficulty: "1", Rating: "3" },
    {
      Name: "Aranka",
      Project: "W5D5 - Project - Lil_Playlist",
      Difficulty: "3",
      Rating: "2",
    },
    { Name: "Aranka", Project: "W6D1-1", Difficulty: "1", Rating: "1" },
    { Name: "Aranka", Project: "W6D2-1", Difficulty: "2", Rating: "2" },
    {
      Name: "Aranka",
      Project: "W6D2 - Project - Eindopdracht",
      Difficulty: "3",
      Rating: "4",
    },
    { Name: "Floris", Project: "SCRUM", Difficulty: "2", Rating: "1" },
    { Name: "Floris", Project: "W1D1-1", Difficulty: "4", Rating: "3" },
    { Name: "Floris", Project: "W1D2-1", Difficulty: "1", Rating: "2" },
    { Name: "Floris", Project: "W1D2-2", Difficulty: "1", Rating: "4" },
    { Name: "Floris", Project: "W1D2-3", Difficulty: "1", Rating: "4" },
    { Name: "Floris", Project: "W1D2-4", Difficulty: "3", Rating: "4" },
    { Name: "Floris", Project: "W1D2-5", Difficulty: "1", Rating: "3" },
    { Name: "Floris", Project: "W1D3-1", Difficulty: "2", Rating: "4" },
    { Name: "Floris", Project: "W1D3-2", Difficulty: "4", Rating: "4" },
    { Name: "Floris", Project: "W1D3-4", Difficulty: "4", Rating: "2" },
    { Name: "Floris", Project: "W1D3-5", Difficulty: "2", Rating: "4" },
    {
      Name: "Floris",
      Project: "W1D3 - Project - Guess-the-number",
      Difficulty: "2",
      Rating: "2",
    },
    { Name: "Floris", Project: "W1D4-1", Difficulty: "1", Rating: "3" },
    {
      Name: "Floris",
      Project: "W1D4 - Project - Kleurentoggle",
      Difficulty: "4",
      Rating: "3",
    },
    {
      Name: "Floris",
      Project: "W1D5 - Project - Galgje",
      Difficulty: "4",
      Rating: "4",
    },
    { Name: "Floris", Project: "W2D1-1", Difficulty: "2", Rating: "2" },
    { Name: "Floris", Project: "W2D1-2", Difficulty: "4", Rating: "1" },
    { Name: "Floris", Project: "W2D2-1", Difficulty: "4", Rating: "1" },
    { Name: "Floris", Project: "W2D2-2", Difficulty: "2", Rating: "2" },
    { Name: "Floris", Project: "W2D2-3", Difficulty: "4", Rating: "2" },
    { Name: "Floris", Project: "W2D3-1", Difficulty: "1", Rating: "1" },
    { Name: "Floris", Project: "W2D3-2", Difficulty: "1", Rating: "2" },
    { Name: "Floris", Project: "W2D3-3", Difficulty: "3", Rating: "3" },
    { Name: "Floris", Project: "W2D4-1", Difficulty: "4", Rating: "4" },
    { Name: "Floris", Project: "W2D4-2", Difficulty: "3", Rating: "1" },
    { Name: "Floris", Project: "W2D4-3", Difficulty: "4", Rating: "1" },
    {
      Name: "Floris",
      Project: "W2D5 - Project - Filmzoeker",
      Difficulty: "4",
      Rating: "1",
    },
    { Name: "Floris", Project: "W3D1-1", Difficulty: "4", Rating: "3" },
    { Name: "Floris", Project: "W3D1-2", Difficulty: "2", Rating: "3" },
    { Name: "Floris", Project: "W3D1-3", Difficulty: "2", Rating: "3" },
    { Name: "Floris", Project: "W3D1-4", Difficulty: "3", Rating: "3" },
    { Name: "Floris", Project: "W3D2-1", Difficulty: "3", Rating: "2" },
    { Name: "Floris", Project: "W3D2-2", Difficulty: "2", Rating: "2" },
    { Name: "Floris", Project: "W3D2-3", Difficulty: "3", Rating: "2" },
    { Name: "Floris", Project: "W3D3-1", Difficulty: "4", Rating: "4" },
    { Name: "Floris", Project: "W3D3-2", Difficulty: "2", Rating: "4" },
    { Name: "Floris", Project: "W3D3-3", Difficulty: "2", Rating: "1" },
    { Name: "Floris", Project: "W3D3-4", Difficulty: "3", Rating: "2" },
    { Name: "Floris", Project: "W3D4-1", Difficulty: "1", Rating: "3" },
    { Name: "Floris", Project: "W3D4-2", Difficulty: "2", Rating: "2" },
    {
      Name: "Floris",
      Project: "W3D5 - Project - Todo-List",
      Difficulty: "4",
      Rating: "2",
    },
    { Name: "Floris", Project: "W4D2-1", Difficulty: "1", Rating: "4" },
    { Name: "Floris", Project: "W4D2-2", Difficulty: "2", Rating: "3" },
    { Name: "Floris", Project: "W4D2-3", Difficulty: "2", Rating: "4" },
    { Name: "Floris", Project: "W4D2-4", Difficulty: "1", Rating: "2" },
    { Name: "Floris", Project: "W4D3-1", Difficulty: "1", Rating: "4" },
    { Name: "Floris", Project: "W4D3-2", Difficulty: "4", Rating: "4" },
    { Name: "Floris", Project: "W4D3-3", Difficulty: "3", Rating: "2" },
    { Name: "Floris", Project: "W4D3-4", Difficulty: "2", Rating: "2" },
    { Name: "Floris", Project: "W4D3-5", Difficulty: "4", Rating: "1" },
    {
      Name: "Floris",
      Project: "W4D3 - Project - Next-Level CSS",
      Difficulty: "2",
      Rating: "2",
    },
    { Name: "Floris", Project: "W5D4-1", Difficulty: "1", Rating: "3" },
    {
      Name: "Floris",
      Project: "W5D5 - Project - Lil_Playlist",
      Difficulty: "3",
      Rating: "1",
    },
    { Name: "Floris", Project: "W6D1-1", Difficulty: "3", Rating: "2" },
    { Name: "Floris", Project: "W6D2-1", Difficulty: "1", Rating: "1" },
    {
      Name: "Floris",
      Project: "W6D2 - Project - Eindopdracht",
      Difficulty: "4",
      Rating: "1",
    },
    { Name: "Hector", Project: "SCRUM", Difficulty: "1", Rating: "2" },
    { Name: "Hector", Project: "W1D1-1", Difficulty: "1", Rating: "4" },
    { Name: "Hector", Project: "W1D2-1", Difficulty: "2", Rating: "4" },
    { Name: "Hector", Project: "W1D2-2", Difficulty: "2", Rating: "3" },
    { Name: "Hector", Project: "W1D2-3", Difficulty: "1", Rating: "2" },
    { Name: "Hector", Project: "W1D2-4", Difficulty: "1", Rating: "3" },
    { Name: "Hector", Project: "W1D2-5", Difficulty: "3", Rating: "1" },
    { Name: "Hector", Project: "W1D3-1", Difficulty: "1", Rating: "4" },
    { Name: "Hector", Project: "W1D3-2", Difficulty: "4", Rating: "3" },
    { Name: "Hector", Project: "W1D3-4", Difficulty: "3", Rating: "1" },
    { Name: "Hector", Project: "W1D3-5", Difficulty: "4", Rating: "2" },
    {
      Name: "Hector",
      Project: "W1D3 - Project - Guess-the-number",
      Difficulty: "3",
      Rating: "1",
    },
    { Name: "Hector", Project: "W1D4-1", Difficulty: "1", Rating: "1" },
    {
      Name: "Hector",
      Project: "W1D4 - Project - Kleurentoggle",
      Difficulty: "1",
      Rating: "3",
    },
    {
      Name: "Hector",
      Project: "W1D5 - Project - Galgje",
      Difficulty: "2",
      Rating: "4",
    },
    { Name: "Hector", Project: "W2D1-1", Difficulty: "4", Rating: "4" },
    { Name: "Hector", Project: "W2D1-2", Difficulty: "3", Rating: "2" },
    { Name: "Hector", Project: "W2D2-1", Difficulty: "4", Rating: "3" },
    { Name: "Hector", Project: "W2D2-2", Difficulty: "1", Rating: "2" },
    { Name: "Hector", Project: "W2D2-3", Difficulty: "3", Rating: "2" },
    { Name: "Hector", Project: "W2D3-1", Difficulty: "3", Rating: "1" },
    { Name: "Hector", Project: "W2D3-2", Difficulty: "4", Rating: "2" },
    { Name: "Hector", Project: "W2D3-3", Difficulty: "4", Rating: "2" },
    { Name: "Hector", Project: "W2D4-1", Difficulty: "2", Rating: "4" },
    { Name: "Hector", Project: "W2D4-2", Difficulty: "4", Rating: "1" },
    { Name: "Hector", Project: "W2D4-3", Difficulty: "3", Rating: "2" },
    {
      Name: "Hector",
      Project: "W2D5 - Project - Filmzoeker",
      Difficulty: "4",
      Rating: "1",
    },
    { Name: "Hector", Project: "W3D1-1", Difficulty: "1", Rating: "1" },
    { Name: "Hector", Project: "W3D1-2", Difficulty: "1", Rating: "4" },
    { Name: "Hector", Project: "W3D1-3", Difficulty: "3", Rating: "2" },
    { Name: "Hector", Project: "W3D1-4", Difficulty: "4", Rating: "3" },
    { Name: "Hector", Project: "W3D2-1", Difficulty: "1", Rating: "3" },
    { Name: "Hector", Project: "W3D2-2", Difficulty: "4", Rating: "3" },
    { Name: "Hector", Project: "W3D2-3", Difficulty: "2", Rating: "1" },
    { Name: "Hector", Project: "W3D3-1", Difficulty: "4", Rating: "4" },
    { Name: "Hector", Project: "W3D3-2", Difficulty: "3", Rating: "1" },
    { Name: "Hector", Project: "W3D3-3", Difficulty: "2", Rating: "4" },
    { Name: "Hector", Project: "W3D3-4", Difficulty: "4", Rating: "1" },
    { Name: "Hector", Project: "W3D4-1", Difficulty: "3", Rating: "4" },
    { Name: "Hector", Project: "W3D4-2", Difficulty: "1", Rating: "4" },
    {
      Name: "Hector",
      Project: "W3D5 - Project - Todo-List",
      Difficulty: "2",
      Rating: "4",
    },
    { Name: "Hector", Project: "W4D2-1", Difficulty: "1", Rating: "1" },
    { Name: "Hector", Project: "W4D2-2", Difficulty: "2", Rating: "1" },
    { Name: "Hector", Project: "W4D2-3", Difficulty: "3", Rating: "3" },
    { Name: "Hector", Project: "W4D2-4", Difficulty: "1", Rating: "3" },
    { Name: "Hector", Project: "W4D3-1", Difficulty: "3", Rating: "3" },
    { Name: "Hector", Project: "W4D3-2", Difficulty: "1", Rating: "4" },
    { Name: "Hector", Project: "W4D3-3", Difficulty: "3", Rating: "1" },
    { Name: "Hector", Project: "W4D3-4", Difficulty: "1", Rating: "3" },
    { Name: "Hector", Project: "W4D3-5", Difficulty: "1", Rating: "2" },
    {
      Name: "Hector",
      Project: "W4D3 - Project - Next-Level CSS",
      Difficulty: "3",
      Rating: "1",
    },
    { Name: "Hector", Project: "W5D4-1", Difficulty: "3", Rating: "4" },
    {
      Name: "Hector",
      Project: "W5D5 - Project - Lil_Playlist",
      Difficulty: "3",
      Rating: "1",
    },
    { Name: "Hector", Project: "W6D1-1", Difficulty: "1", Rating: "1" },
    { Name: "Hector", Project: "W6D2-1", Difficulty: "4", Rating: "2" },
    {
      Name: "Hector",
      Project: "W6D2 - Project - Eindopdracht",
      Difficulty: "2",
      Rating: "4",
    },
    { Name: "Martina", Project: "SCRUM", Difficulty: "1", Rating: "1" },
    { Name: "Martina", Project: "W1D1-1", Difficulty: "4", Rating: "1" },
    { Name: "Martina", Project: "W1D2-1", Difficulty: "3", Rating: "3" },
    { Name: "Martina", Project: "W1D2-2", Difficulty: "2", Rating: "1" },
    { Name: "Martina", Project: "W1D2-3", Difficulty: "2", Rating: "1" },
    { Name: "Martina", Project: "W1D2-4", Difficulty: "4", Rating: "2" },
    { Name: "Martina", Project: "W1D2-5", Difficulty: "3", Rating: "4" },
    { Name: "Martina", Project: "W1D3-1", Difficulty: "3", Rating: "4" },
    { Name: "Martina", Project: "W1D3-2", Difficulty: "2", Rating: "1" },
    { Name: "Martina", Project: "W1D3-4", Difficulty: "3", Rating: "2" },
    { Name: "Martina", Project: "W1D3-5", Difficulty: "1", Rating: "1" },
    {
      Name: "Martina",
      Project: "W1D3 - Project - Guess-the-number",
      Difficulty: "2",
      Rating: "2",
    },
    { Name: "Martina", Project: "W1D4-1", Difficulty: "4", Rating: "2" },
    {
      Name: "Martina",
      Project: "W1D4 - Project - Kleurentoggle",
      Difficulty: "1",
      Rating: "3",
    },
    {
      Name: "Martina",
      Project: "W1D5 - Project - Galgje",
      Difficulty: "1",
      Rating: "4",
    },
    { Name: "Martina", Project: "W2D1-1", Difficulty: "1", Rating: "4" },
    { Name: "Martina", Project: "W2D1-2", Difficulty: "4", Rating: "2" },
    { Name: "Martina", Project: "W2D2-1", Difficulty: "4", Rating: "1" },
    { Name: "Martina", Project: "W2D2-2", Difficulty: "3", Rating: "3" },
    { Name: "Martina", Project: "W2D2-3", Difficulty: "3", Rating: "1" },
    { Name: "Martina", Project: "W2D3-1", Difficulty: "4", Rating: "2" },
    { Name: "Martina", Project: "W2D3-2", Difficulty: "3", Rating: "4" },
    { Name: "Martina", Project: "W2D3-3", Difficulty: "3", Rating: "3" },
    { Name: "Martina", Project: "W2D4-1", Difficulty: "1", Rating: "4" },
    { Name: "Martina", Project: "W2D4-2", Difficulty: "3", Rating: "4" },
    { Name: "Martina", Project: "W2D4-3", Difficulty: "3", Rating: "4" },
    {
      Name: "Martina",
      Project: "W2D5 - Project - Filmzoeker",
      Difficulty: "2",
      Rating: "4",
    },
    { Name: "Martina", Project: "W3D1-1", Difficulty: "1", Rating: "1" },
    { Name: "Martina", Project: "W3D1-2", Difficulty: "3", Rating: "3" },
    { Name: "Martina", Project: "W3D1-3", Difficulty: "3", Rating: "1" },
    { Name: "Martina", Project: "W3D1-4", Difficulty: "3", Rating: "2" },
    { Name: "Martina", Project: "W3D2-1", Difficulty: "1", Rating: "2" },
    { Name: "Martina", Project: "W3D2-2", Difficulty: "2", Rating: "4" },
    { Name: "Martina", Project: "W3D2-3", Difficulty: "3", Rating: "1" },
    { Name: "Martina", Project: "W3D3-1", Difficulty: "1", Rating: "4" },
    { Name: "Martina", Project: "W3D3-2", Difficulty: "4", Rating: "1" },
    { Name: "Martina", Project: "W3D3-3", Difficulty: "3", Rating: "3" },
    { Name: "Martina", Project: "W3D3-4", Difficulty: "2", Rating: "3" },
    { Name: "Martina", Project: "W3D4-1", Difficulty: "4", Rating: "4" },
    { Name: "Martina", Project: "W3D4-2", Difficulty: "3", Rating: "1" },
    {
      Name: "Martina",
      Project: "W3D5 - Project - Todo-List",
      Difficulty: "2",
      Rating: "3",
    },
    { Name: "Martina", Project: "W4D2-1", Difficulty: "3", Rating: "4" },
    { Name: "Martina", Project: "W4D2-2", Difficulty: "1", Rating: "2" },
    { Name: "Martina", Project: "W4D2-3", Difficulty: "3", Rating: "4" },
    { Name: "Martina", Project: "W4D2-4", Difficulty: "4", Rating: "1" },
    { Name: "Martina", Project: "W4D3-1", Difficulty: "2", Rating: "4" },
    { Name: "Martina", Project: "W4D3-2", Difficulty: "1", Rating: "3" },
    { Name: "Martina", Project: "W4D3-3", Difficulty: "2", Rating: "4" },
    { Name: "Martina", Project: "W4D3-4", Difficulty: "4", Rating: "1" },
    { Name: "Martina", Project: "W4D3-5", Difficulty: "3", Rating: "2" },
    {
      Name: "Martina",
      Project: "W4D3 - Project - Next-Level CSS",
      Difficulty: "3",
      Rating: "4",
    },
    { Name: "Martina", Project: "W5D4-1", Difficulty: "1", Rating: "4" },
    {
      Name: "Martina",
      Project: "W5D5 - Project - Lil_Playlist",
      Difficulty: "1",
      Rating: "1",
    },
    { Name: "Martina", Project: "W6D1-1", Difficulty: "2", Rating: "1" },
    { Name: "Martina", Project: "W6D2-1", Difficulty: "1", Rating: "4" },
    {
      Name: "Martina",
      Project: "W6D2 - Project - Eindopdracht",
      Difficulty: "1",
      Rating: "4",
    },
    { Name: "Maurits", Project: "SCRUM", Difficulty: "3", Rating: "4" },
    { Name: "Maurits", Project: "W1D1-1", Difficulty: "4", Rating: "3" },
    { Name: "Maurits", Project: "W1D2-1", Difficulty: "2", Rating: "2" },
    { Name: "Maurits", Project: "W1D2-2", Difficulty: "1", Rating: "4" },
    { Name: "Maurits", Project: "W1D2-3", Difficulty: "2", Rating: "2" },
    { Name: "Maurits", Project: "W1D2-4", Difficulty: "3", Rating: "1" },
    { Name: "Maurits", Project: "W1D2-5", Difficulty: "2", Rating: "3" },
    { Name: "Maurits", Project: "W1D3-1", Difficulty: "2", Rating: "4" },
    { Name: "Maurits", Project: "W1D3-2", Difficulty: "2", Rating: "2" },
    { Name: "Maurits", Project: "W1D3-4", Difficulty: "2", Rating: "2" },
    { Name: "Maurits", Project: "W1D3-5", Difficulty: "1", Rating: "3" },
    {
      Name: "Maurits",
      Project: "W1D3 - Project - Guess-the-number",
      Difficulty: "1",
      Rating: "1",
    },
    { Name: "Maurits", Project: "W1D4-1", Difficulty: "3", Rating: "4" },
    {
      Name: "Maurits",
      Project: "W1D4 - Project - Kleurentoggle",
      Difficulty: "4",
      Rating: "1",
    },
    {
      Name: "Maurits",
      Project: "W1D5 - Project - Galgje",
      Difficulty: "3",
      Rating: "2",
    },
    { Name: "Maurits", Project: "W2D1-1", Difficulty: "1", Rating: "1" },
    { Name: "Maurits", Project: "W2D1-2", Difficulty: "2", Rating: "3" },
    { Name: "Maurits", Project: "W2D2-1", Difficulty: "1", Rating: "2" },
    { Name: "Maurits", Project: "W2D2-2", Difficulty: "4", Rating: "1" },
    { Name: "Maurits", Project: "W2D2-3", Difficulty: "2", Rating: "2" },
    { Name: "Maurits", Project: "W2D3-1", Difficulty: "2", Rating: "2" },
    { Name: "Maurits", Project: "W2D3-2", Difficulty: "3", Rating: "3" },
    { Name: "Maurits", Project: "W2D3-3", Difficulty: "2", Rating: "1" },
    { Name: "Maurits", Project: "W2D4-1", Difficulty: "1", Rating: "3" },
    { Name: "Maurits", Project: "W2D4-2", Difficulty: "3", Rating: "2" },
    { Name: "Maurits", Project: "W2D4-3", Difficulty: "3", Rating: "3" },
    {
      Name: "Maurits",
      Project: "W2D5 - Project - Filmzoeker",
      Difficulty: "3",
      Rating: "1",
    },
    { Name: "Maurits", Project: "W3D1-1", Difficulty: "4", Rating: "4" },
    { Name: "Maurits", Project: "W3D1-2", Difficulty: "1", Rating: "3" },
    { Name: "Maurits", Project: "W3D1-3", Difficulty: "1", Rating: "4" },
    { Name: "Maurits", Project: "W3D1-4", Difficulty: "1", Rating: "2" },
    { Name: "Maurits", Project: "W3D2-1", Difficulty: "1", Rating: "4" },
    { Name: "Maurits", Project: "W3D2-2", Difficulty: "1", Rating: "1" },
    { Name: "Maurits", Project: "W3D2-3", Difficulty: "4", Rating: "3" },
    { Name: "Maurits", Project: "W3D3-1", Difficulty: "1", Rating: "1" },
    { Name: "Maurits", Project: "W3D3-2", Difficulty: "2", Rating: "1" },
    { Name: "Maurits", Project: "W3D3-3", Difficulty: "1", Rating: "3" },
    { Name: "Maurits", Project: "W3D3-4", Difficulty: "4", Rating: "1" },
    { Name: "Maurits", Project: "W3D4-1", Difficulty: "4", Rating: "4" },
    { Name: "Maurits", Project: "W3D4-2", Difficulty: "1", Rating: "3" },
    {
      Name: "Maurits",
      Project: "W3D5 - Project - Todo-List",
      Difficulty: "3",
      Rating: "4",
    },
    { Name: "Maurits", Project: "W4D2-1", Difficulty: "3", Rating: "1" },
    { Name: "Maurits", Project: "W4D2-2", Difficulty: "4", Rating: "4" },
    { Name: "Maurits", Project: "W4D2-3", Difficulty: "4", Rating: "1" },
    { Name: "Maurits", Project: "W4D2-4", Difficulty: "2", Rating: "3" },
    { Name: "Maurits", Project: "W4D3-1", Difficulty: "3", Rating: "1" },
    { Name: "Maurits", Project: "W4D3-2", Difficulty: "3", Rating: "2" },
    { Name: "Maurits", Project: "W4D3-3", Difficulty: "3", Rating: "4" },
    { Name: "Maurits", Project: "W4D3-4", Difficulty: "1", Rating: "3" },
    { Name: "Maurits", Project: "W4D3-5", Difficulty: "2", Rating: "1" },
    {
      Name: "Maurits",
      Project: "W4D3 - Project - Next-Level CSS",
      Difficulty: "2",
      Rating: "3",
    },
    { Name: "Maurits", Project: "W5D4-1", Difficulty: "1", Rating: "3" },
    {
      Name: "Maurits",
      Project: "W5D5 - Project - Lil_Playlist",
      Difficulty: "4",
      Rating: "2",
    },
    { Name: "Maurits", Project: "W6D1-1", Difficulty: "1", Rating: "3" },
    { Name: "Maurits", Project: "W6D2-1", Difficulty: "1", Rating: "4" },
    {
      Name: "Maurits",
      Project: "W6D2 - Project - Eindopdracht",
      Difficulty: "3",
      Rating: "3",
    },
    { Name: "Rahima", Project: "SCRUM", Difficulty: "2", Rating: "4" },
    { Name: "Rahima", Project: "W1D1-1", Difficulty: "3", Rating: "4" },
    { Name: "Rahima", Project: "W1D2-1", Difficulty: "2", Rating: "4" },
    { Name: "Rahima", Project: "W1D2-2", Difficulty: "1", Rating: "2" },
    { Name: "Rahima", Project: "W1D2-3", Difficulty: "1", Rating: "3" },
    { Name: "Rahima", Project: "W1D2-4", Difficulty: "1", Rating: "2" },
    { Name: "Rahima", Project: "W1D2-5", Difficulty: "1", Rating: "3" },
    { Name: "Rahima", Project: "W1D3-1", Difficulty: "1", Rating: "1" },
    { Name: "Rahima", Project: "W1D3-2", Difficulty: "2", Rating: "4" },
    { Name: "Rahima", Project: "W1D3-4", Difficulty: "1", Rating: "2" },
    { Name: "Rahima", Project: "W1D3-5", Difficulty: "2", Rating: "2" },
    {
      Name: "Rahima",
      Project: "W1D3 - Project - Guess-the-number",
      Difficulty: "3",
      Rating: "1",
    },
    { Name: "Rahima", Project: "W1D4-1", Difficulty: "4", Rating: "3" },
    {
      Name: "Rahima",
      Project: "W1D4 - Project - Kleurentoggle",
      Difficulty: "2",
      Rating: "4",
    },
    {
      Name: "Rahima",
      Project: "W1D5 - Project - Galgje",
      Difficulty: "3",
      Rating: "3",
    },
    { Name: "Rahima", Project: "W2D1-1", Difficulty: "2", Rating: "2" },
    { Name: "Rahima", Project: "W2D1-2", Difficulty: "3", Rating: "1" },
    { Name: "Rahima", Project: "W2D2-1", Difficulty: "1", Rating: "1" },
    { Name: "Rahima", Project: "W2D2-2", Difficulty: "1", Rating: "1" },
    { Name: "Rahima", Project: "W2D2-3", Difficulty: "4", Rating: "2" },
    { Name: "Rahima", Project: "W2D3-1", Difficulty: "1", Rating: "1" },
    { Name: "Rahima", Project: "W2D3-2", Difficulty: "1", Rating: "4" },
    { Name: "Rahima", Project: "W2D3-3", Difficulty: "4", Rating: "2" },
    { Name: "Rahima", Project: "W2D4-1", Difficulty: "4", Rating: "4" },
    { Name: "Rahima", Project: "W2D4-2", Difficulty: "4", Rating: "4" },
    { Name: "Rahima", Project: "W2D4-3", Difficulty: "2", Rating: "3" },
    {
      Name: "Rahima",
      Project: "W2D5 - Project - Filmzoeker",
      Difficulty: "3",
      Rating: "1",
    },
    { Name: "Rahima", Project: "W3D1-1", Difficulty: "1", Rating: "1" },
    { Name: "Rahima", Project: "W3D1-2", Difficulty: "1", Rating: "2" },
    { Name: "Rahima", Project: "W3D1-3", Difficulty: "2", Rating: "3" },
    { Name: "Rahima", Project: "W3D1-4", Difficulty: "2", Rating: "4" },
    { Name: "Rahima", Project: "W3D2-1", Difficulty: "3", Rating: "2" },
    { Name: "Rahima", Project: "W3D2-2", Difficulty: "1", Rating: "4" },
    { Name: "Rahima", Project: "W3D2-3", Difficulty: "2", Rating: "1" },
    { Name: "Rahima", Project: "W3D3-1", Difficulty: "3", Rating: "1" },
    { Name: "Rahima", Project: "W3D3-2", Difficulty: "4", Rating: "4" },
    { Name: "Rahima", Project: "W3D3-3", Difficulty: "1", Rating: "4" },
    { Name: "Rahima", Project: "W3D3-4", Difficulty: "2", Rating: "2" },
    { Name: "Rahima", Project: "W3D4-1", Difficulty: "1", Rating: "2" },
    { Name: "Rahima", Project: "W3D4-2", Difficulty: "3", Rating: "3" },
    {
      Name: "Rahima",
      Project: "W3D5 - Project - Todo-List",
      Difficulty: "2",
      Rating: "4",
    },
    { Name: "Rahima", Project: "W4D2-1", Difficulty: "2", Rating: "4" },
    { Name: "Rahima", Project: "W4D2-2", Difficulty: "4", Rating: "3" },
    { Name: "Rahima", Project: "W4D2-3", Difficulty: "3", Rating: "3" },
    { Name: "Rahima", Project: "W4D2-4", Difficulty: "4", Rating: "1" },
    { Name: "Rahima", Project: "W4D3-1", Difficulty: "2", Rating: "1" },
    { Name: "Rahima", Project: "W4D3-2", Difficulty: "1", Rating: "1" },
    { Name: "Rahima", Project: "W4D3-3", Difficulty: "2", Rating: "1" },
    { Name: "Rahima", Project: "W4D3-4", Difficulty: "2", Rating: "2" },
    { Name: "Rahima", Project: "W4D3-5", Difficulty: "3", Rating: "2" },
    {
      Name: "Rahima",
      Project: "W4D3 - Project - Next-Level CSS",
      Difficulty: "1",
      Rating: "2",
    },
    { Name: "Rahima", Project: "W5D4-1", Difficulty: "3", Rating: "3" },
    {
      Name: "Rahima",
      Project: "W5D5 - Project - Lil_Playlist",
      Difficulty: "2",
      Rating: "3",
    },
    { Name: "Rahima", Project: "W6D1-1", Difficulty: "4", Rating: "4" },
    { Name: "Rahima", Project: "W6D2-1", Difficulty: "1", Rating: "4" },
    {
      Name: "Rahima",
      Project: "W6D2 - Project - Eindopdracht",
      Difficulty: "4",
      Rating: "1",
    },
    { Name: "Sandra", Project: "SCRUM", Difficulty: "4", Rating: "1" },
    { Name: "Sandra", Project: "W1D1-1", Difficulty: "2", Rating: "4" },
    { Name: "Sandra", Project: "W1D2-1", Difficulty: "3", Rating: "4" },
    { Name: "Sandra", Project: "W1D2-2", Difficulty: "3", Rating: "2" },
    { Name: "Sandra", Project: "W1D2-3", Difficulty: "3", Rating: "4" },
    { Name: "Sandra", Project: "W1D2-4", Difficulty: "3", Rating: "1" },
    { Name: "Sandra", Project: "W1D2-5", Difficulty: "4", Rating: "3" },
    { Name: "Sandra", Project: "W1D3-1", Difficulty: "1", Rating: "1" },
    { Name: "Sandra", Project: "W1D3-2", Difficulty: "1", Rating: "1" },
    { Name: "Sandra", Project: "W1D3-4", Difficulty: "3", Rating: "3" },
    { Name: "Sandra", Project: "W1D3-5", Difficulty: "4", Rating: "3" },
    {
      Name: "Sandra",
      Project: "W1D3 - Project - Guess-the-number",
      Difficulty: "2",
      Rating: "4",
    },
    { Name: "Sandra", Project: "W1D4-1", Difficulty: "3", Rating: "2" },
    {
      Name: "Sandra",
      Project: "W1D4 - Project - Kleurentoggle",
      Difficulty: "1",
      Rating: "3",
    },
    {
      Name: "Sandra",
      Project: "W1D5 - Project - Galgje",
      Difficulty: "3",
      Rating: "3",
    },
    { Name: "Sandra", Project: "W2D1-1", Difficulty: "4", Rating: "1" },
    { Name: "Sandra", Project: "W2D1-2", Difficulty: "4", Rating: "3" },
    { Name: "Sandra", Project: "W2D2-1", Difficulty: "3", Rating: "4" },
    { Name: "Sandra", Project: "W2D2-2", Difficulty: "2", Rating: "3" },
    { Name: "Sandra", Project: "W2D2-3", Difficulty: "4", Rating: "3" },
    { Name: "Sandra", Project: "W2D3-1", Difficulty: "1", Rating: "2" },
    { Name: "Sandra", Project: "W2D3-2", Difficulty: "3", Rating: "2" },
    { Name: "Sandra", Project: "W2D3-3", Difficulty: "2", Rating: "2" },
    { Name: "Sandra", Project: "W2D4-1", Difficulty: "1", Rating: "3" },
    { Name: "Sandra", Project: "W2D4-2", Difficulty: "2", Rating: "4" },
    { Name: "Sandra", Project: "W2D4-3", Difficulty: "2", Rating: "2" },
    {
      Name: "Sandra",
      Project: "W2D5 - Project - Filmzoeker",
      Difficulty: "2",
      Rating: "4",
    },
    { Name: "Sandra", Project: "W3D1-1", Difficulty: "3", Rating: "3" },
    { Name: "Sandra", Project: "W3D1-2", Difficulty: "3", Rating: "4" },
    { Name: "Sandra", Project: "W3D1-3", Difficulty: "2", Rating: "4" },
    { Name: "Sandra", Project: "W3D1-4", Difficulty: "2", Rating: "2" },
    { Name: "Sandra", Project: "W3D2-1", Difficulty: "2", Rating: "4" },
    { Name: "Sandra", Project: "W3D2-2", Difficulty: "2", Rating: "3" },
    { Name: "Sandra", Project: "W3D2-3", Difficulty: "1", Rating: "2" },
    { Name: "Sandra", Project: "W3D3-1", Difficulty: "1", Rating: "2" },
    { Name: "Sandra", Project: "W3D3-2", Difficulty: "2", Rating: "2" },
    { Name: "Sandra", Project: "W3D3-3", Difficulty: "4", Rating: "4" },
    { Name: "Sandra", Project: "W3D3-4", Difficulty: "3", Rating: "2" },
    { Name: "Sandra", Project: "W3D4-1", Difficulty: "2", Rating: "3" },
    { Name: "Sandra", Project: "W3D4-2", Difficulty: "1", Rating: "1" },
    {
      Name: "Sandra",
      Project: "W3D5 - Project - Todo-List",
      Difficulty: "1",
      Rating: "2",
    },
    { Name: "Sandra", Project: "W4D2-1", Difficulty: "3", Rating: "3" },
    { Name: "Sandra", Project: "W4D2-2", Difficulty: "1", Rating: "1" },
    { Name: "Sandra", Project: "W4D2-3", Difficulty: "3", Rating: "4" },
    { Name: "Sandra", Project: "W4D2-4", Difficulty: "1", Rating: "4" },
    { Name: "Sandra", Project: "W4D3-1", Difficulty: "3", Rating: "1" },
    { Name: "Sandra", Project: "W4D3-2", Difficulty: "1", Rating: "3" },
    { Name: "Sandra", Project: "W4D3-3", Difficulty: "2", Rating: "4" },
    { Name: "Sandra", Project: "W4D3-4", Difficulty: "1", Rating: "4" },
    { Name: "Sandra", Project: "W4D3-5", Difficulty: "1", Rating: "3" },
    {
      Name: "Sandra",
      Project: "W4D3 - Project - Next-Level CSS",
      Difficulty: "3",
      Rating: "4",
    },
    { Name: "Sandra", Project: "W5D4-1", Difficulty: "1", Rating: "1" },
    {
      Name: "Sandra",
      Project: "W5D5 - Project - Lil_Playlist",
      Difficulty: "2",
      Rating: "2",
    },
    { Name: "Sandra", Project: "W6D1-1", Difficulty: "1", Rating: "4" },
    { Name: "Sandra", Project: "W6D2-1", Difficulty: "2", Rating: "3" },
    {
      Name: "Sandra",
      Project: "W6D2 - Project - Eindopdracht",
      Difficulty: "4",
      Rating: "1",
    },
    { Name: "Wietske", Project: "SCRUM", Difficulty: "1", Rating: "1" },
    { Name: "Wietske", Project: "W1D1-1", Difficulty: "4", Rating: "3" },
    { Name: "Wietske", Project: "W1D2-1", Difficulty: "1", Rating: "4" },
    { Name: "Wietske", Project: "W1D2-2", Difficulty: "1", Rating: "2" },
    { Name: "Wietske", Project: "W1D2-3", Difficulty: "2", Rating: "3" },
    { Name: "Wietske", Project: "W1D2-4", Difficulty: "2", Rating: "1" },
    { Name: "Wietske", Project: "W1D2-5", Difficulty: "3", Rating: "4" },
    { Name: "Wietske", Project: "W1D3-1", Difficulty: "1", Rating: "2" },
    { Name: "Wietske", Project: "W1D3-2", Difficulty: "1", Rating: "4" },
    { Name: "Wietske", Project: "W1D3-4", Difficulty: "2", Rating: "1" },
    { Name: "Wietske", Project: "W1D3-5", Difficulty: "3", Rating: "4" },
    {
      Name: "Wietske",
      Project: "W1D3 - Project - Guess-the-number",
      Difficulty: "2",
      Rating: "4",
    },
    { Name: "Wietske", Project: "W1D4-1", Difficulty: "2", Rating: "4" },
    {
      Name: "Wietske",
      Project: "W1D4 - Project - Kleurentoggle",
      Difficulty: "2",
      Rating: "3",
    },
    {
      Name: "Wietske",
      Project: "W1D5 - Project - Galgje",
      Difficulty: "3",
      Rating: "3",
    },
    { Name: "Wietske", Project: "W2D1-1", Difficulty: "3", Rating: "1" },
    { Name: "Wietske", Project: "W2D1-2", Difficulty: "4", Rating: "1" },
    { Name: "Wietske", Project: "W2D2-1", Difficulty: "2", Rating: "2" },
    { Name: "Wietske", Project: "W2D2-2", Difficulty: "2", Rating: "4" },
    { Name: "Wietske", Project: "W2D2-3", Difficulty: "3", Rating: "4" },
    { Name: "Wietske", Project: "W2D3-1", Difficulty: "2", Rating: "1" },
    { Name: "Wietske", Project: "W2D3-2", Difficulty: "1", Rating: "1" },
    { Name: "Wietske", Project: "W2D3-3", Difficulty: "2", Rating: "3" },
    { Name: "Wietske", Project: "W2D4-1", Difficulty: "1", Rating: "1" },
    { Name: "Wietske", Project: "W2D4-2", Difficulty: "2", Rating: "4" },
    { Name: "Wietske", Project: "W2D4-3", Difficulty: "4", Rating: "3" },
    {
      Name: "Wietske",
      Project: "W2D5 - Project - Filmzoeker",
      Difficulty: "2",
      Rating: "2",
    },
    { Name: "Wietske", Project: "W3D1-1", Difficulty: "1", Rating: "3" },
    { Name: "Wietske", Project: "W3D1-2", Difficulty: "4", Rating: "4" },
    { Name: "Wietske", Project: "W3D1-3", Difficulty: "4", Rating: "2" },
    { Name: "Wietske", Project: "W3D1-4", Difficulty: "1", Rating: "4" },
    { Name: "Wietske", Project: "W3D2-1", Difficulty: "3", Rating: "2" },
    { Name: "Wietske", Project: "W3D2-2", Difficulty: "1", Rating: "3" },
    { Name: "Wietske", Project: "W3D2-3", Difficulty: "2", Rating: "4" },
    { Name: "Wietske", Project: "W3D3-1", Difficulty: "1", Rating: "4" },
    { Name: "Wietske", Project: "W3D3-2", Difficulty: "3", Rating: "1" },
    { Name: "Wietske", Project: "W3D3-3", Difficulty: "1", Rating: "3" },
    { Name: "Wietske", Project: "W3D3-4", Difficulty: "3", Rating: "4" },
    { Name: "Wietske", Project: "W3D4-1", Difficulty: "3", Rating: "4" },
    { Name: "Wietske", Project: "W3D4-2", Difficulty: "4", Rating: "2" },
    {
      Name: "Wietske",
      Project: "W3D5 - Project - Todo-List",
      Difficulty: "2",
      Rating: "4",
    },
    { Name: "Wietske", Project: "W4D2-1", Difficulty: "3", Rating: "3" },
    { Name: "Wietske", Project: "W4D2-2", Difficulty: "2", Rating: "4" },
    { Name: "Wietske", Project: "W4D2-3", Difficulty: "1", Rating: "2" },
    { Name: "Wietske", Project: "W4D2-4", Difficulty: "4", Rating: "3" },
    { Name: "Wietske", Project: "W4D3-1", Difficulty: "2", Rating: "1" },
    { Name: "Wietske", Project: "W4D3-2", Difficulty: "1", Rating: "2" },
    { Name: "Wietske", Project: "W4D3-3", Difficulty: "1", Rating: "4" },
    { Name: "Wietske", Project: "W4D3-4", Difficulty: "3", Rating: "4" },
    { Name: "Wietske", Project: "W4D3-5", Difficulty: "4", Rating: "3" },
    {
      Name: "Wietske",
      Project: "W4D3 - Project - Next-Level CSS",
      Difficulty: "4",
      Rating: "2",
    },
    { Name: "Wietske", Project: "W5D4-1", Difficulty: "3", Rating: "1" },
    {
      Name: "Wietske",
      Project: "W5D5 - Project - Lil_Playlist",
      Difficulty: "4",
      Rating: "2",
    },
    { Name: "Wietske", Project: "W6D1-1", Difficulty: "1", Rating: "1" },
    { Name: "Wietske", Project: "W6D2-1", Difficulty: "2", Rating: "1" },
    {
      Name: "Wietske",
      Project: "W6D2 - Project - Eindopdracht",
      Difficulty: "1",
      Rating: "2",
    },
    { Name: "Storm", Project: "SCRUM", Difficulty: "1", Rating: "1" },
    { Name: "Storm", Project: "W1D1-1", Difficulty: "2", Rating: "2" },
    { Name: "Storm", Project: "W1D2-1", Difficulty: "2", Rating: "3" },
    { Name: "Storm", Project: "W1D2-2", Difficulty: "1", Rating: "3" },
    { Name: "Storm", Project: "W1D2-3", Difficulty: "1", Rating: "2" },
    { Name: "Storm", Project: "W1D2-4", Difficulty: "4", Rating: "3" },
    { Name: "Storm", Project: "W1D2-5", Difficulty: "3", Rating: "3" },
    { Name: "Storm", Project: "W1D3-1", Difficulty: "2", Rating: "3" },
    { Name: "Storm", Project: "W1D3-2", Difficulty: "1", Rating: "1" },
    { Name: "Storm", Project: "W1D3-4", Difficulty: "1", Rating: "1" },
    { Name: "Storm", Project: "W1D3-5", Difficulty: "2", Rating: "2" },
    {
      Name: "Storm",
      Project: "W1D3 - Project - Guess-the-number",
      Difficulty: "3",
      Rating: "4",
    },
    { Name: "Storm", Project: "W1D4-1", Difficulty: "4", Rating: "2" },
    {
      Name: "Storm",
      Project: "W1D4 - Project - Kleurentoggle",
      Difficulty: "3",
      Rating: "2",
    },
    {
      Name: "Storm",
      Project: "W1D5 - Project - Galgje",
      Difficulty: "4",
      Rating: "4",
    },
    { Name: "Storm", Project: "W2D1-1", Difficulty: "2", Rating: "4" },
    { Name: "Storm", Project: "W2D1-2", Difficulty: "3", Rating: "2" },
    { Name: "Storm", Project: "W2D2-1", Difficulty: "4", Rating: "4" },
    { Name: "Storm", Project: "W2D2-2", Difficulty: "2", Rating: "1" },
    { Name: "Storm", Project: "W2D2-3", Difficulty: "1", Rating: "1" },
    { Name: "Storm", Project: "W2D3-1", Difficulty: "2", Rating: "3" },
    { Name: "Storm", Project: "W2D3-2", Difficulty: "3", Rating: "4" },
    { Name: "Storm", Project: "W2D3-3", Difficulty: "3", Rating: "2" },
    { Name: "Storm", Project: "W2D4-1", Difficulty: "3", Rating: "4" },
    { Name: "Storm", Project: "W2D4-2", Difficulty: "4", Rating: "3" },
    { Name: "Storm", Project: "W2D4-3", Difficulty: "2", Rating: "1" },
    {
      Name: "Storm",
      Project: "W2D5 - Project - Filmzoeker",
      Difficulty: "4",
      Rating: "1",
    },
    { Name: "Storm", Project: "W3D1-1", Difficulty: "2", Rating: "1" },
    { Name: "Storm", Project: "W3D1-2", Difficulty: "2", Rating: "2" },
    { Name: "Storm", Project: "W3D1-3", Difficulty: "1", Rating: "2" },
    { Name: "Storm", Project: "W3D1-4", Difficulty: "2", Rating: "3" },
    { Name: "Storm", Project: "W3D2-1", Difficulty: "1", Rating: "4" },
    { Name: "Storm", Project: "W3D2-2", Difficulty: "3", Rating: "3" },
    { Name: "Storm", Project: "W3D2-3", Difficulty: "3", Rating: "4" },
    { Name: "Storm", Project: "W3D3-1", Difficulty: "3", Rating: "4" },
    { Name: "Storm", Project: "W3D3-2", Difficulty: "1", Rating: "2" },
    { Name: "Storm", Project: "W3D3-3", Difficulty: "3", Rating: "1" },
    { Name: "Storm", Project: "W3D3-4", Difficulty: "3", Rating: "1" },
    { Name: "Storm", Project: "W3D4-1", Difficulty: "2", Rating: "4" },
    { Name: "Storm", Project: "W3D4-2", Difficulty: "3", Rating: "4" },
    {
      Name: "Storm",
      Project: "W3D5 - Project - Todo-List",
      Difficulty: "3",
      Rating: "2",
    },
    { Name: "Storm", Project: "W4D2-1", Difficulty: "2", Rating: "1" },
    { Name: "Storm", Project: "W4D2-2", Difficulty: "3", Rating: "3" },
    { Name: "Storm", Project: "W4D2-3", Difficulty: "2", Rating: "2" },
    { Name: "Storm", Project: "W4D2-4", Difficulty: "3", Rating: "4" },
    { Name: "Storm", Project: "W4D3-1", Difficulty: "3", Rating: "4" },
    { Name: "Storm", Project: "W4D3-2", Difficulty: "2", Rating: "3" },
    { Name: "Storm", Project: "W4D3-3", Difficulty: "1", Rating: "1" },
    { Name: "Storm", Project: "W4D3-4", Difficulty: "3", Rating: "1" },
    { Name: "Storm", Project: "W4D3-5", Difficulty: "2", Rating: "3" },
    {
      Name: "Storm",
      Project: "W4D3 - Project - Next-Level CSS",
      Difficulty: "4",
      Rating: "1",
    },
    { Name: "Storm", Project: "W5D4-1", Difficulty: "2", Rating: "2" },
    {
      Name: "Storm",
      Project: "W5D5 - Project - Lil_Playlist",
      Difficulty: "1",
      Rating: "2",
    },
    { Name: "Storm", Project: "W6D1-1", Difficulty: "4", Rating: "4" },
    { Name: "Storm", Project: "W6D2-1", Difficulty: "1", Rating: "1" },
    {
      Name: "Storm",
      Project: "W6D2 - Project - Eindopdracht",
      Difficulty: "3",
      Rating: "3",
    },
  ],
};

export default StudentData;
